/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.automostate;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Jp Miravalles
 */
public class adminMain extends javax.swing.JFrame {
    int mousepX;
    int mousepY;
    /**
     * Creates new form adminMain
     */
    public adminMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        fullscreenPanel = new javax.swing.JPanel();
        Fullscreen = new javax.swing.JLabel();
        iconifyPanel = new javax.swing.JPanel();
        Iconify = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        lineMenu = new javax.swing.JPanel();
        menuButton = new javax.swing.JPanel();
        menuButtonIcon = new javax.swing.JLabel();
        menuHide = new javax.swing.JPanel();
        dashboardView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(255, 204, 0));
        Header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Header.setPreferredSize(new java.awt.Dimension(1400, 50));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon("D:\\Jp Miravalles\\Desktop\\Auto-mo-status3.png")); // NOI18N
        Logo.setText("jLabel3");
        Header.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 8, 37, -1));

        exitPanel.setBackground(new java.awt.Color(255, 204, 0));
        exitPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exitPanel.setPreferredSize(new java.awt.Dimension(50, 50));
        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPanelMouseExited(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Akira Expanded", 0, 36)); // NOI18N
        Exit.setText("x");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(Exit))
        );

        Header.add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, -1, 49));

        fullscreenPanel.setBackground(new java.awt.Color(255, 204, 0));
        fullscreenPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fullscreenPanel.setPreferredSize(new java.awt.Dimension(50, 50));
        fullscreenPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullscreenPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullscreenPanelMouseExited(evt);
            }
        });

        Fullscreen.setFont(new java.awt.Font("Akira Expanded", 0, 36)); // NOI18N
        Fullscreen.setText("O");
        Fullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullscreenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FullscreenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullscreenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fullscreenPanelLayout = new javax.swing.GroupLayout(fullscreenPanel);
        fullscreenPanel.setLayout(fullscreenPanelLayout);
        fullscreenPanelLayout.setHorizontalGroup(
            fullscreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fullscreenPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fullscreen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fullscreenPanelLayout.setVerticalGroup(
            fullscreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fullscreenPanelLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(Fullscreen))
        );

        Header.add(fullscreenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, -1, 49));

        iconifyPanel.setBackground(new java.awt.Color(255, 204, 0));
        iconifyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iconifyPanel.setPreferredSize(new java.awt.Dimension(50, 50));
        iconifyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconifyPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconifyPanelMouseExited(evt);
            }
        });

        Iconify.setFont(new java.awt.Font("Akira Expanded", 0, 36)); // NOI18N
        Iconify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Iconify.setText("-");
        Iconify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconifyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout iconifyPanelLayout = new javax.swing.GroupLayout(iconifyPanel);
        iconifyPanel.setLayout(iconifyPanelLayout);
        iconifyPanelLayout.setHorizontalGroup(
            iconifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iconifyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Iconify, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        iconifyPanelLayout.setVerticalGroup(
            iconifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iconifyPanelLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(Iconify))
        );

        Header.add(iconifyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, -1, 49));

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setPreferredSize(new java.awt.Dimension(270, 450));
        Menu.setLayout(new java.awt.BorderLayout());

        menuIcon.setBackground(new java.awt.Color(255, 204, 0));
        menuIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineMenu.setBackground(new java.awt.Color(255, 204, 0));
        lineMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lineMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineMenuLayout = new javax.swing.GroupLayout(lineMenu);
        lineMenu.setLayout(lineMenuLayout);
        lineMenuLayout.setHorizontalGroup(
            lineMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        lineMenuLayout.setVerticalGroup(
            lineMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        menuIcon.add(lineMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 10));

        menuButton.setBackground(new java.awt.Color(255, 204, 0));
        menuButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuButton.setPreferredSize(new java.awt.Dimension(50, 50));
        menuButton.setLayout(new java.awt.BorderLayout());

        menuButtonIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuButtonIcon.setIcon(new javax.swing.ImageIcon("D:\\Jp Miravalles\\Downloads\\icons8-menu-40.png")); // NOI18N
        menuButtonIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuButtonIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuButtonIconMouseExited(evt);
            }
        });
        menuButton.add(menuButtonIcon, java.awt.BorderLayout.CENTER);

        menuIcon.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        Menu.add(menuIcon, java.awt.BorderLayout.LINE_START);

        menuHide.setBackground(new java.awt.Color(111, 111, 111));

        javax.swing.GroupLayout menuHideLayout = new javax.swing.GroupLayout(menuHide);
        menuHide.setLayout(menuHideLayout);
        menuHideLayout.setHorizontalGroup(
            menuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        menuHideLayout.setVerticalGroup(
            menuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Menu.add(menuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        dashboardView.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout dashboardViewLayout = new javax.swing.GroupLayout(dashboardView);
        dashboardView.setLayout(dashboardViewLayout);
        dashboardViewLayout.setHorizontalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        dashboardViewLayout.setVerticalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(dashboardView, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor (JPanel hover, Color rand){
        hover.setBackground(rand);
    }    
    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        
        this.setLocation(kordinatX - mousepX, kordinatY - mousepY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void FullscreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullscreenMouseClicked
        if (this.getExtendedState()!=adminMain.MAXIMIZED_BOTH){
            this.setExtendedState(adminMain.MAXIMIZED_BOTH);
        }
        else {
            this.setExtendedState(adminMain.NORMAL);
        }
    }//GEN-LAST:event_FullscreenMouseClicked

    private void IconifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconifyMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_IconifyMouseClicked

    private void exitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseEntered
        changecolor(exitPanel, new Color (255, 217, 67));
    }//GEN-LAST:event_exitPanelMouseEntered

    private void exitPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseExited
        changecolor(exitPanel, new Color (255, 204, 0));
    }//GEN-LAST:event_exitPanelMouseExited

    private void fullscreenPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullscreenPanelMouseEntered
        changecolor(fullscreenPanel, new Color (255, 217, 67));
    }//GEN-LAST:event_fullscreenPanelMouseEntered

    private void fullscreenPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullscreenPanelMouseExited
        changecolor(fullscreenPanel, new Color (255, 204, 0));
    }//GEN-LAST:event_fullscreenPanelMouseExited

    private void iconifyPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconifyPanelMouseEntered
        changecolor(iconifyPanel, new Color (255, 217, 67));
    }//GEN-LAST:event_iconifyPanelMouseEntered

    private void iconifyPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconifyPanelMouseExited
        changecolor(iconifyPanel, new Color (255, 204, 0));
    }//GEN-LAST:event_iconifyPanelMouseExited

    private void FullscreenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullscreenMouseEntered
        changecolor(fullscreenPanel, new Color (255, 217, 67));
    }//GEN-LAST:event_FullscreenMouseEntered

    private void FullscreenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullscreenMouseExited
        changecolor(fullscreenPanel, new Color (255, 204, 0));
    }//GEN-LAST:event_FullscreenMouseExited

    private void IconifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconifyMouseEntered
        changecolor(iconifyPanel, new Color (255, 217, 67));
    }//GEN-LAST:event_IconifyMouseEntered

    private void IconifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconifyMouseExited
        changecolor(iconifyPanel, new Color (255, 204, 0));
    }//GEN-LAST:event_IconifyMouseExited

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        changecolor(exitPanel, new Color (255, 217, 67));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        changecolor(exitPanel, new Color (255, 204, 0));
    }//GEN-LAST:event_ExitMouseExited

    private void menuButtonIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonIconMouseEntered
        changecolor(menuButton, new Color (255, 217, 67));
    }//GEN-LAST:event_menuButtonIconMouseEntered

    private void menuButtonIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuButtonIconMouseClicked

    private void menuButtonIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonIconMouseExited
        changecolor(menuButton, new Color (255, 204, 0));
    }//GEN-LAST:event_menuButtonIconMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Fullscreen;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Iconify;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel dashboardView;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JPanel fullscreenPanel;
    private javax.swing.JPanel iconifyPanel;
    private javax.swing.JPanel lineMenu;
    private javax.swing.JPanel menuButton;
    private javax.swing.JLabel menuButtonIcon;
    private javax.swing.JPanel menuHide;
    private javax.swing.JPanel menuIcon;
    // End of variables declaration//GEN-END:variables
}
