/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.automostate;

import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jp Miravalles
 */
public class Login extends javax.swing.JFrame {
    int mousepX;
    int mousepY;
    static String user;
    static String pass;
    /**
     * Creates new form Login
     */
        private static final int CORNER_RADIUS = 20;
    public Login() {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), CORNER_RADIUS, CORNER_RADIUS));
        leftPanel.setBackground(new Color(255,204,0,230));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        Iconify = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        AboutUsText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        userTitle = new javax.swing.JLabel();
        passTitle = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        passCheck = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();
        lockIcon = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        topPanel.setBackground(new java.awt.Color(255, 204, 0));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        Iconify.setFont(new java.awt.Font("Akira Expanded", 0, 24)); // NOI18N
        Iconify.setText("-");
        Iconify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Iconify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconifyMouseClicked(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Akira Expanded", 0, 24)); // NOI18N
        Exit.setText("X");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(539, Short.MAX_VALUE)
                .addComponent(Iconify)
                .addGap(12, 12, 12)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Iconify)
                .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel);
        topPanel.setBounds(0, 0, 600, 30);

        Title.setBackground(new java.awt.Color(51, 51, 51));
        Title.setFont(new java.awt.Font("Akira Expanded", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 51));
        Title.setText("uto-Mo-Status");

        AboutUsText.setBackground(new java.awt.Color(51, 51, 51));
        AboutUsText.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        AboutUsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutUsText.setText("<html><center>Secure Your Parking, Secure Your Car: Choose Auto-Mo-Status. </center></html>");

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Jp Miravalles\\Desktop\\Auto-mo-status3.png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(AboutUsText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Title)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(AboutUsText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        getContentPane().add(leftPanel);
        leftPanel.setBounds(0, 30, 300, 370);

        rightPanel.setBackground(new java.awt.Color(51, 51, 51));

        userTitle.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        userTitle.setForeground(new java.awt.Color(255, 204, 0));
        userTitle.setText("Username");

        passTitle.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        passTitle.setForeground(new java.awt.Color(255, 204, 0));
        passTitle.setText("Password");

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        passCheck.setBackground(new java.awt.Color(51, 51, 51));
        passCheck.setForeground(new java.awt.Color(255, 204, 0));
        passCheck.setText("Show Password");
        passCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passCheckActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(255, 204, 0));
        loginButton.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        loginButton.setText("Log-in as Administrator");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        lockIcon.setIcon(new javax.swing.ImageIcon("D:\\Jp Miravalles\\Downloads\\icons8-lock-20.jpg")); // NOI18N

        userIcon.setIcon(new javax.swing.ImageIcon("D:\\Jp Miravalles\\Downloads\\icons8-person-20.png")); // NOI18N

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(rightPanelLayout.createSequentialGroup()
                                .addComponent(lockIcon)
                                .addGap(7, 7, 7))
                            .addGroup(rightPanelLayout.createSequentialGroup()
                                .addComponent(userIcon)
                                .addGap(6, 6, 6)))
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passCheck)
                            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Password)
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passTitle)
                                .addComponent(userTitle)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(userTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addComponent(userIcon)
                        .addGap(31, 31, 31))
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addComponent(lockIcon)
                        .addGap(10, 10, 10)))
                .addComponent(passCheck)
                .addGap(26, 26, 26)
                .addComponent(loginButton)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        getContentPane().add(rightPanel);
        rightPanel.setBounds(300, 30, 300, 370);

        Background.setIcon(new javax.swing.ImageIcon("D:\\Jp Miravalles\\Downloads\\ParkingBackground.jpg")); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(300, 370));
        getContentPane().add(Background);
        Background.setBounds(0, 30, 300, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void topPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_topPanelMouseClicked

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        
        this.setLocation(kordinatX - mousepX, kordinatY - mousepY);
    }//GEN-LAST:event_topPanelMouseDragged

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void IconifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconifyMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_IconifyMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String enteredUser = Username.getText();
        String enteredPass = new String(Password.getPassword());
        if (enteredUser.equals("masterclassadmin01") && enteredPass.equals("tuviy67$32ll")) {
            adminMain mn = new adminMain();
            mn.setVisible(true);
            mn.pack();
            mn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passCheckActionPerformed
        // TODO add your handling code here:
        if(passCheck.isSelected()){
            Password.setEchoChar((char)0);
        } else {
            Password.setEchoChar(('*'));
        }
    }//GEN-LAST:event_passCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutUsText;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Iconify;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel lockIcon;
    private javax.swing.JButton loginButton;
    private javax.swing.JCheckBox passCheck;
    private javax.swing.JLabel passTitle;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userTitle;
    // End of variables declaration//GEN-END:variables
}
